### ISSUE TITLE
Add metor

### ISSUE THREAD

**Issue by szymag** [szymag/radar#1]
On radar should be displayed meteors instead of planes.

**Comment by hryniuk** [comment]
Images:
![meteor0_red](https://user-images.githubusercontent.com/344521/39235270-fb43bfe2-4864-11e8-9153-bd74e54db303.png)
![meteor0_green](https://user-images.githubusercontent.com/344521/39235271-fb6987fe-4864-11e8-90af-e8b78a5a0072.png)

**Comment by szymag** [comment]
Thank you. They're awesome!!
